### ISSUE TITLE
SynthMusic

### ISSUE THREAD

**Issue by The65Dude** [Rtxeon/Rtxeon#1]
Hey did the SynthMusic bot got deleted? or what happened to it?

**Comment by Rtxeon** [comment]
I had to delete it

**Comment by Rtxeon** [comment]
Coz it was in beta

**Comment by Rtxeon** [comment]
This 5th september v1 of synth will be realeased

**Comment by Rtxeon** [comment]
And you also know msg commands are gonna disappear from discord

**Comment by Rtxeon** [comment]
So migrating

**Comment by The65Dude** [comment]
Yeah it's gonna be all slash commands

**Comment by The65Dude** [comment]
i had a little bot but it messed up and i don't have much experience in js
for discord bots so idk how to fix it

**Comment by The65Dude** [comment]
would love to learn tho

**Comment by The65Dude** [comment]
Would u mind if i add u on discord?

**Comment by Rtxeon** [comment]
I would not mind my username is Rtxeon@1337
